### ISSUE TITLE
sshkeys::manual error on creating .ssh folder under user's home dir

### ISSUE THREAD

**Issue by nandha027** [GeoffWilliams/sshkeys#6] opened 2021-01-29 11:43 UTC
sshkeys::manual errors on line 117 as it cant create .ssh folder under user's home directory as it already exists and permission of user's home folder is 777 . So if we push the code through puppet root user cant create .ssh folder due to permission issue .

**Comment by GeoffWilliams** [comment] 2021-02-02 03:53
Not able to reproduce this with information given:

```shell
[root@a7dd31dfc7e4 /]# mkdir /home/alice
[root@a7dd31dfc7e4 /]# mkdir /home/alice/.ssh
[root@a7dd31dfc7e4 /]# chmod 777 /home/alice/
[root@a7dd31dfc7e4 /]# puppet apply /testcase/examples/manual.pp 
Notice: Compiled catalog for a7dd31dfc7e4 in environment production in 0.05 seconds
Notice: /Stage[main]/Main/File[/home/alice]/owner: owner changed 'root' to 'alice'
Notice: /Stage[main]/Main/File[/home/alice]/group: group changed 'root' to 'alice'
Notice: /Stage[main]/Main/Sshkeys::Manual[alice]/File[/home/alice/.ssh]/owner: owner changed 'root' to 'alice'
Notice: /Stage[main]/Main/Sshkeys::Manual[alice]/File[/home/alice/.ssh]/group: group changed 'root' to 'alice'
Notice: /Stage[main]/Main/Sshkeys::Manual[alice]/File[/home/alice/.ssh]/mode: mode changed '0755' to '0700'
Notice: /Stage[main]/Main/Sshkeys::Manual[alice]/File[/home/alice/.ssh/id_rsa]/ensure: defined content as '{md5}bd5cb935bd0e6bc38d09674b01db3694'
Notice: /Stage[main]/Main/Sshkeys::Manual[alice]/File[/home/alice/.ssh/id_rsa.pub]/ensure: defined content as '{md5}ad2e0b06017ee400c447a39701575748'
Notice: /Stage[main]/Main/Sshkeys::Manual[alice]/File[/home/alice/.ssh/authorized_keys]/ensure: defined content as '{md5}87e26278a3a019e1977ffa07c0d047bc'
Notice: /Stage[main]/Main/Sshkeys::Manual[alice]/File[/home/alice/.ssh/known_hosts]/ensure: defined content as '{md5}9c62e483f7c75349e0ed4c91daabb75f'
Notice: Applied catalog in 0.10 seconds
[root@a7dd31dfc7e4 /]# ls -ld /home/alice/.ssh/
drwx------ 2 alice alice 4096 Feb  2 03:45 /home/alice/.ssh/
```

Puppet shouldn't worry if the directory already exists unless its not running as `root` or the `immutable` bit is set - see https://linoxide.com/how-tos/change-attributes-of-file/

I'm not working on this module at the moment but happy to review a pull request if you find the error - thanks

**Comment by nandha027** [comment] 2021-02-02 04:31
Hi GeoffWilliams ,
Actually my concern is that we need to create .ssh directory manually
before we run the ssh keys module. But I want the module itself to check
for .ssh directory , if it's not exists should create and add rsa keys to
that directory .

Regards,
Nandha

**Comment by GeoffWilliams** [comment] 2021-02-02 04:34
That's what I did in my test:

```
[root@a7dd31dfc7e4 /]# mkdir /home/alice
[root@a7dd31dfc7e4 /]# mkdir /home/alice/.ssh
[root@a7dd31dfc7e4 /]# chmod 777 /home/alice/
```

_then run puppet_

Seems to work?

**Comment by nandha027** [comment] 2021-02-02 06:19
Hi geoff,

Yes it works if we create .ssh dir manually . But i need that step within
puppet code itself .which reduce our work as we have hundreds of users in
our Active Directory .

Regards,
Nandha

**Comment by GeoffWilliams** [comment] 2021-02-02 06:28
I retested with no `.ssh` directory and it works fine:

```
[root@a7dd31dfc7e4 /]# rm -rf /home/alice 
[root@a7dd31dfc7e4 /]# mkdir /home/alice
[root@a7dd31dfc7e4 /]# chmod 777 /home/alice
[root@a7dd31dfc7e4 /]# puppet apply /testcase/examples/manual.pp 
Notice: Compiled catalog for a7dd31dfc7e4 in environment production in 0.05 seconds
Notice: /Stage[main]/Main/File[/home/alice]/owner: owner changed 'root' to 'alice'
Notice: /Stage[main]/Main/File[/home/alice]/group: group changed 'root' to 'alice'
Notice: /Stage[main]/Main/Sshkeys::Manual[alice]/File[/home/alice/.ssh]/ensure: created
Notice: /Stage[main]/Main/Sshkeys::Manual[alice]/File[/home/alice/.ssh/id_rsa]/ensure: defined content as '{md5}bd5cb935bd0e6bc38d09674b01db3694'
Notice: /Stage[main]/Main/Sshkeys::Manual[alice]/File[/home/alice/.ssh/id_rsa.pub]/ensure: defined content as '{md5}ad2e0b06017ee400c447a39701575748'
Notice: /Stage[main]/Main/Sshkeys::Manual[alice]/File[/home/alice/.ssh/authorized_keys]/ensure: defined content as '{md5}87e26278a3a019e1977ffa07c0d047bc'
Notice: /Stage[main]/Main/Sshkeys::Manual[alice]/File[/home/alice/.ssh/known_hosts]/ensure: defined content as '{md5}9c62e483f7c75349e0ed4c91daabb75f'
Notice: Applied catalog in 0.08 seconds
[root@a7dd31dfc7e4 /]# ls -l /home/alice/.ssh
total 16
-rw------- 1 alice alice  781 Feb  2 06:20 authorized_keys
-rw------- 1 alice alice 1675 Feb  2 06:20 id_rsa
-rw------- 1 alice alice  392 Feb  2 06:20 id_rsa.pub
-rw------- 1 alice alice  171 Feb  2 06:20 known_hosts
```

Do you mean you want this to work if the user homedir does **not** exist?  In that case you would expect this error:

```
[root@a7dd31dfc7e4 /]# rm /home/alice/ -rf

# testcase adjusted to not create homedir
[root@a7dd31dfc7e4 /]# puppet apply /testcase/examples/manual.pp 
Notice: Compiled catalog for a7dd31dfc7e4 in environment production in 0.05 seconds
Error: Cannot create /home/alice/.ssh; parent directory /home/alice does not exist
Error: /Stage[main]/Main/Sshkeys::Manual[alice]/File[/home/alice/.ssh]/ensure: change from 'absent' to 'directory' failed: Cannot create /home/alice/.ssh; parent directory /home/alice does not exist
Notice: /Stage[main]/Main/Sshkeys::Manual[alice]/File[/home/alice/.ssh/id_rsa]: Dependency File[/home/alice/.ssh] has failures: true
Warning: /Stage[main]/Main/Sshkeys::Manual[alice]/File[/home/alice/.ssh/id_rsa]: Skipping because of failed dependencies
Notice: /Stage[main]/Main/Sshkeys::Manual[alice]/File[/home/alice/.ssh/id_rsa.pub]: Dependency File[/home/alice/.ssh] has failures: true
Warning: /Stage[main]/Main/Sshkeys::Manual[alice]/File[/home/alice/.ssh/id_rsa.pub]: Skipping because of failed dependencies
Notice: /Stage[main]/Main/Sshkeys::Manual[alice]/File[/home/alice/.ssh/authorized_keys]: Dependency File[/home/alice/.ssh] has failures: true
Warning: /Stage[main]/Main/Sshkeys::Manual[alice]/File[/home/alice/.ssh/authorized_keys]: Skipping because of failed dependencies
Notice: /Stage[main]/Main/Sshkeys::Manual[alice]/File[/home/alice/.ssh/known_hosts]: Dependency File[/home/alice/.ssh] has failures: true
Warning: /Stage[main]/Main/Sshkeys::Manual[alice]/File[/home/alice/.ssh/known_hosts]: Skipping because of failed dependencies
Notice: Applied catalog in 0.05 seconds
```

If this is the problem, you need another tool (or more puppet code) to create the homedirs before you run this module. 

This module is not the right place to do it, especially if you need to integrate AD.

**Comment by nandha027** [comment] 2021-02-02 06:39
Yes , error your receive is same I facing . What kind of tool could use to
create home dir before running puppet .

**Comment by GeoffWilliams** [comment] 2021-02-02 06:44
Maybe look at realmd/sssd? I think this one sets up homedirs for you. There are a bunch of other tools too, pretty sure I had a customer use centrify before and that worked too.

Closing as this is `not-a-bug`

**Closed as completed by GeoffWilliams** 2021-02-02 06:44 UTC
